---
region: 'eu-west-1'

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: "%{hiera('deployment_identifier')}-public.example"
private_domain_name: "%{hiera('deployment_identifier')}-private.example"
