---
configuration_directory: "%{cwd}/examples/full"
state_file: "%{cwd}/state/full.tfstate"
vars:
  region: "%{hiera('region')}"

  domain_name: "%{hiera('domain_name')}"
  private_domain_name: "%{hiera('private_domain_name')}"
